name: "Setup Playwright Environment"
description: "Install dependencies, cache browsers, install Playwright browsers, and Japanese fonts"

runs:
  using: "composite"
  steps:
    # GitHub Actionsのキャッシュを設定
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: tests/e2e-tests/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('tests/e2e-tests/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    # 依存関係をインストール
    - name: Install dependencies
      run: npm ci
      working-directory: tests/e2e-tests
      shell: bash
