name: Generate Critical CSS

on:
  # push トリガーにする場合はブランチを制御してくださいb
  push:
    branches: [criticalcss検証]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'criticalcss')
    strategy:
      matrix:
        page:
          - { url: "/", target: "home2.css" }
          - { url: "/lunch_box/", target: "post.css" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install critical
        run: npm install -g critical

      - name: Generate critical CSS
        run: |
          base_url="https://wpdev.auroralab-design.com${{ matrix.page.url }}"
          mkdir -p css/critical
          npx critical $base_url \
            --width 412 \
            --height 823 \
            --inline false \
            --extract false \
            --target css/critical/${{ matrix.page.target }} \
            --css \
              css/src/base-style.css \
              css/src/front.css \
              css/src/helper.css \
              css/src/home.css \
              css/src/home1.css \
              css/src/home2.css \
              css/src/integlight-menu.css \
              css/src/integlight-slide-style.css \
              css/src/integlight-sp-style.css \
              css/src/integlight-style.css \
              css/src/layout.css \
              css/src/module.css \
              css/src/page.css \
              css/src/post.css \
              css/src/svg-non-home.css \
              https://wpdev.auroralab-design.com/wp-content/plugins/aurora-design-blocks/css/src/aurora-design.css \
              https://wpdev.auroralab-design.com/wp-content/plugins/aurora-design-blocks/css/src/module.css \
              https://wpdev.auroralab-design.com/wp-includes/css/dist/block-library/style.min.css

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add css/critical
          git commit -m "chore: update critical.css [skip ci]" || echo "No changes to commit"
          git push
