name: Generate Critical CSS

on:
  push:
    branches: [criticalcss検証]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'criticalcss')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install critical
        run: npm install -g critical

      - name: Generate all critical CSS
        run: |
          mkdir -p css/critical
          declare -A pages
          pages["/"]="home2.css"
          pages["/lunch_box/"]="post.css"

          for url in "${!pages[@]}"; do
            target="${pages[$url]}"
            base_url="https://t2.auroralab-design.com${url}"
            npx critical "$base_url" \
              --width 412 \
              --height 823 \
              --inline false \
              --extract false \
              --target "css/critical/$target" \
              --css \
                css/src/base-style.css \
                css/src/front.css \
                css/src/helper.css \
                css/src/home.css \
                css/src/home1.css \
                css/src/home2.css \
                css/src/integlight-menu.css \
                css/src/integlight-slide-style.css \
                css/src/integlight-sp-style.css \
                css/src/integlight-style.css \
                css/src/layout.css \
                css/src/module.css \
                css/src/page.css \
                css/src/post.css \
                css/src/svg-non-home.css \
                https://t2.auroralab-design.com/wp-content/plugins/aurora-design-blocks/css/src/aurora-design.css \
                https://t2.auroralab-design.com/wp-content/plugins/aurora-design-blocks/css/src/module.css \
                https://t2.auroralab-design.com/wp-includes/css/dist/block-library/style.min.css
          done

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add css/critical
          git commit -m "chore: update critical.css [skip ci]" || echo "No changes to commit"
          git push
