name: Playwright general Test
#gtest a
on:
  push:
    branches: [dev]
  pull_request:
  workflow_dispatch:

jobs:
  general-test:
    if: contains(github.event.head_commit.message, 'gtest')
    runs-on: ubuntu-latest
    container:
      # 公式のPlaywrightイメージを使用x
      image: mcr.microsoft.com/playwright:v1.51.1-jammy

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 7. storage state 保存用ディレクトリ作成
      - name: Setup Playwright Environment
        uses: ./.github/actions/setup-playwright

      # # 7. storage state 保存用ディレクトリ作成
      # - name: Prepare auth directory
      #   run: mkdir -p playwright/.auth
      #   working-directory: tests/e2e-tests

      # # 8. 認証用 setup プロジェクト実行
      # - name: Run Playwright auth setup
      #   run: npx playwright test --project=setup --config=playwright.config.js
      #   working-directory: tests/e2e-tests
      # #######################################################
      # 9. general(汎用a) テスト実行
      - name: Run Playwright general tests
        run: |

          npx playwright test tests/e2e-tests/tests/01_customiser.color.spec.ts --project=main --project=unauthenticated --config=playwright.config.js --reporter=html 
          #npx playwright test tests/e2e-tests/tests/01_customiser.color.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/03_customiser.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/04_header.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/05_htmlCode.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/07_pf.image.home.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/08_pf.regOuterAssets.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/10_slider.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #npx playwright test tests/e2e-tests/tests/11_headerImage.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
          #DEBUG=pw:api npx playwright test tests/e2e-tests/tests/10_slider.spec.ts --project=main --project=unauthenticated --config=playwright.config.js
        working-directory: tests/e2e-tests
      # #######################################################

      - name: Move HTML report
        run: mv playwright-report test-results/
        working-directory: tests/e2e-tests

      # 10. テスト結果・スクリーンショットをアーティファクトとして保存
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            tests/e2e-tests/test-results/
