name: Playwright Compare Visual Test
#test2
on:
  push:
    branches: [ githubでplaywright ]
  pull_request:
  workflow_dispatch:

jobs:
  visual-test:
    if: contains(github.event.head_commit.message, 'vtest')
    runs-on: ubuntu-latest

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
      # Playwright ブラウザをプロジェクト配下に配置（キャッシュ対象）
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/tests/e2e-tests/.playwright-browsers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Playwright ブラウザのキャッシュ（追加箇所） ---
      - name: Ensure playwright browsers dir exists
        run: mkdir -p .playwright-browsers
        working-directory: tests/e2e-tests

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: tests/e2e-tests/.playwright-browsers
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('tests/e2e-tests/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - name: Install Playwright browsers (skip if cache hit)
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
        working-directory: tests/e2e-tests
      # --- /追加箇所 ---

      # ---

      ## NodeモジュールとPlaywrightブラウザのキャッシュとインストール


      # 2. 依存関係のインストール（tests/e2e-tests用）
      - name: Install e2e-test dependencies
        run: npm ci
        working-directory: tests/e2e-tests


      # 4. Playwrightブラウザインストール
      # （上でキャッシュの有無に応じて実行済み／スキップされるため、ここは不要のままコメントアウトしています）
      # - name: Install Playwright browsers
      #   run: npx playwright install  --with-deps
      #   working-directory: tests/e2e-tests

      # ---

      ## テストの実行と結果の処理

      # 5. storage state 保存用ディレクトリ作成
      - name: Prepare auth directory
        run: mkdir -p playwright/.auth
        working-directory: tests/e2e-tests

      # 6. 認証用セットアッププロジェクト実行
      - name: Run Playwright auth setup
        run: npx playwright test --project=setup --config=playwright.config.js
        working-directory: tests/e2e-tests

      # 7. visualテスト実行
      - name: Run Playwright visual tests
        run: npx playwright test --project=visual --config=playwright.config.js
        working-directory: tests/e2e-tests

      # 8. テスト結果・スクリーンショットをアーティファクトとして保存
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            tests/e2e-tests/test-results/

      # 9. テスト結果をコミット
      - name: Commit updated test result
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/e2e-tests/test-results/
          git commit -m "Update test result [ci skip]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
