name: Playwright Visual Test
#test
on:
  push:
    branches: [ githubでplaywright ]
  pull_request:
  workflow_dispatch:

jobs:
  visual-test:
    runs-on: ubuntu-latest

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ここからカレントディレクトリを tests/e2e-tests に変更
      - name: Prepare auth directory
        run: mkdir -p playwright/.auth
        working-directory: tests/e2e-tests

      - name: Run Playwright auth setup
        run: npx playwright test --project=setup --config=playwright.config.js
        working-directory: tests/e2e-tests

      - name: Run Playwright visual tests
        run: npx playwright test --project=visual --config=playwright.config.js
        working-directory: tests/e2e-tests

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            tests/screenshots
            tests/playwright-report
        working-directory: tests/e2e-tests
