name: Playwright function Test

on:
  push:
    branches: [ githubでplaywright ]
  pull_request:
  workflow_dispatch:

jobs:
  function-test:
    runs-on: ubuntu-latest
    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js セットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Node モジュールキャッシュ
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. 依存パッケージインストール（キャッシュがなければ）
      - name: Install dependencies
        run: npm ci

      # 5. Playwright ブラウザキャッシュ
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # 6. Playwright ブラウザインストール（キャッシュがなければ）
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 7. storage state 保存用ディレクトリ作成
      - name: Prepare auth directory
        run: mkdir -p playwright/.auth
        working-directory: tests/e2e-tests

      # 8. 認証用 setup プロジェクト実行
      - name: Run Playwright auth setup
        run: npx playwright test --project=setup --config=playwright.config.js
        working-directory: tests/e2e-tests

      # 9. visual テスト実行
      - name: Run Playwright visual tests
        run: npx playwright test --project=main --project=unauthenticated --config=playwright.config.js
        working-directory: tests/e2e-tests

       # 10. テスト結果・スクリーンショットをアーティファクトとして保存
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            tests/e2e-tests/test-results/