# Release zip
name: Release

on:
  push:
    branches:
      - master # master にマージされたときに実行
jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          zip -r integlight.zip . \
            -x ".*" \
              ".phpcs.xml.dist" \
              ".phpunit.result.cache" \
              "phpunit.xml.dist" \
              "vendor/" "vendor/*" \
              "tests/" "tests/*" \
              "tmp/" "tmp/*" \
              "bin/" "bin/*" \
              "util/" "util/*" \
              "node_modules/" "node_modules/*" \
              "package.json" \
              "package-lock.json" \
              "yarn.lock" \
              "composer.json" \
              "composer.lock" \
              "Gruntfile.js" \
              "gulpfile.js" \
              "webpack.config.js" \
              "postcss.config.js" \
              "babel.config.js" \
              "integlight.zip" \
              "*.log"

      - name: リリースを作成する
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tag_${{ github.ref }}_${{github.sha}}
          release_name: Release ${{ github.ref }}
          body: release body

      - name: リリースアセットをアップロードする
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: integlight.zip
          asset_path: ./integlight.zip
          asset_content_type: application/zip
